CREATE TABLE [dbo].[Post]
(
	[PostId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[Subject] NVARCHAR(256) NOT NULL,
	[Content] NVARCHAR(MAX) NOT NULL,
	[SendDate] DATETIME2 NOT NULL DEFAULT GETDATE(),
	[EmployeeId] UNIQUEIDENTIFIER NOT NULL,
	[ProjectId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [PK_Post] PRIMARY KEY ([PostId]),
	CONSTRAINT [FK_Post_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [Employee]([EmployeeId]),
	CONSTRAINT [FK_Post_Project] FOREIGN KEY ([ProjectId]) REFERENCES [Project]([ProjectId])
)
