CREATE TABLE [dbo].[User]
(
	[UserId] UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	[Email] NVARCHAR(320) NOT NULL,
	[Password] VARBINARY(32) NOT NULL,
	[Salt] UNIQUEIDENTIFIER NOT NULL,
	[EmployeeId] UNIQUEIDENTIFIER NOT NULL,
	CONSTRAINT [PK_User] PRIMARY KEY ([UserId]),
	CONSTRAINT [FK_User_Employee] FOREIGN KEY ([EmployeeId]) REFERENCES [Employee] ([EmployeeId]),
	CONSTRAINT [UK_User_Email] UNIQUE ([Email])
)
